// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: internal/raft/RPC/raft.proto

package RPC

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Command struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Op            string                 `protobuf:"bytes,1,opt,name=op,proto3" json:"op,omitempty"`
	Key           string                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Value         []byte                 `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Command) Reset() {
	*x = Command{}
	mi := &file_internal_raft_RPC_raft_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Command) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Command) ProtoMessage() {}

func (x *Command) ProtoReflect() protoreflect.Message {
	mi := &file_internal_raft_RPC_raft_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Command.ProtoReflect.Descriptor instead.
func (*Command) Descriptor() ([]byte, []int) {
	return file_internal_raft_RPC_raft_proto_rawDescGZIP(), []int{0}
}

func (x *Command) GetOp() string {
	if x != nil {
		return x.Op
	}
	return ""
}

func (x *Command) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *Command) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

type LogEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Term          int64                  `protobuf:"varint,1,opt,name=term,proto3" json:"term,omitempty"`
	Command       *Command               `protobuf:"bytes,2,opt,name=command,proto3" json:"command,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogEntry) Reset() {
	*x = LogEntry{}
	mi := &file_internal_raft_RPC_raft_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogEntry) ProtoMessage() {}

func (x *LogEntry) ProtoReflect() protoreflect.Message {
	mi := &file_internal_raft_RPC_raft_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogEntry.ProtoReflect.Descriptor instead.
func (*LogEntry) Descriptor() ([]byte, []int) {
	return file_internal_raft_RPC_raft_proto_rawDescGZIP(), []int{1}
}

func (x *LogEntry) GetTerm() int64 {
	if x != nil {
		return x.Term
	}
	return 0
}

func (x *LogEntry) GetCommand() *Command {
	if x != nil {
		return x.Command
	}
	return nil
}

type AppendEntriesRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ShardId           string                 `protobuf:"bytes,1,opt,name=shard_id,json=shardId,proto3" json:"shard_id,omitempty"`
	Term              int64                  `protobuf:"varint,2,opt,name=term,proto3" json:"term,omitempty"`
	LeaderId          string                 `protobuf:"bytes,3,opt,name=leader_id,json=leaderId,proto3" json:"leader_id,omitempty"`
	PrevLogIndex      int64                  `protobuf:"varint,4,opt,name=prev_log_index,json=prevLogIndex,proto3" json:"prev_log_index,omitempty"`
	PrevLogTerm       int64                  `protobuf:"varint,5,opt,name=prev_log_term,json=prevLogTerm,proto3" json:"prev_log_term,omitempty"`
	Entries           []*LogEntry            `protobuf:"bytes,6,rep,name=entries,proto3" json:"entries,omitempty"`
	LeaderCommitIndex int64                  `protobuf:"varint,7,opt,name=leader_commit_index,json=leaderCommitIndex,proto3" json:"leader_commit_index,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *AppendEntriesRequest) Reset() {
	*x = AppendEntriesRequest{}
	mi := &file_internal_raft_RPC_raft_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppendEntriesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppendEntriesRequest) ProtoMessage() {}

func (x *AppendEntriesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_raft_RPC_raft_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppendEntriesRequest.ProtoReflect.Descriptor instead.
func (*AppendEntriesRequest) Descriptor() ([]byte, []int) {
	return file_internal_raft_RPC_raft_proto_rawDescGZIP(), []int{2}
}

func (x *AppendEntriesRequest) GetShardId() string {
	if x != nil {
		return x.ShardId
	}
	return ""
}

func (x *AppendEntriesRequest) GetTerm() int64 {
	if x != nil {
		return x.Term
	}
	return 0
}

func (x *AppendEntriesRequest) GetLeaderId() string {
	if x != nil {
		return x.LeaderId
	}
	return ""
}

func (x *AppendEntriesRequest) GetPrevLogIndex() int64 {
	if x != nil {
		return x.PrevLogIndex
	}
	return 0
}

func (x *AppendEntriesRequest) GetPrevLogTerm() int64 {
	if x != nil {
		return x.PrevLogTerm
	}
	return 0
}

func (x *AppendEntriesRequest) GetEntries() []*LogEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

func (x *AppendEntriesRequest) GetLeaderCommitIndex() int64 {
	if x != nil {
		return x.LeaderCommitIndex
	}
	return 0
}

type AppendEntriesReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShardId       string                 `protobuf:"bytes,1,opt,name=shard_id,json=shardId,proto3" json:"shard_id,omitempty"`
	Term          int64                  `protobuf:"varint,2,opt,name=term,proto3" json:"term,omitempty"`
	Success       bool                   `protobuf:"varint,3,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AppendEntriesReply) Reset() {
	*x = AppendEntriesReply{}
	mi := &file_internal_raft_RPC_raft_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppendEntriesReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppendEntriesReply) ProtoMessage() {}

func (x *AppendEntriesReply) ProtoReflect() protoreflect.Message {
	mi := &file_internal_raft_RPC_raft_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppendEntriesReply.ProtoReflect.Descriptor instead.
func (*AppendEntriesReply) Descriptor() ([]byte, []int) {
	return file_internal_raft_RPC_raft_proto_rawDescGZIP(), []int{3}
}

func (x *AppendEntriesReply) GetShardId() string {
	if x != nil {
		return x.ShardId
	}
	return ""
}

func (x *AppendEntriesReply) GetTerm() int64 {
	if x != nil {
		return x.Term
	}
	return 0
}

func (x *AppendEntriesReply) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type RequestVote struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShardId       string                 `protobuf:"bytes,1,opt,name=shard_id,json=shardId,proto3" json:"shard_id,omitempty"`
	Term          int64                  `protobuf:"varint,2,opt,name=term,proto3" json:"term,omitempty"`
	CandidateId   string                 `protobuf:"bytes,3,opt,name=candidate_id,json=candidateId,proto3" json:"candidate_id,omitempty"`
	LastLogIndex  int64                  `protobuf:"varint,4,opt,name=last_log_index,json=lastLogIndex,proto3" json:"last_log_index,omitempty"`
	LastLogTerm   int64                  `protobuf:"varint,5,opt,name=last_log_term,json=lastLogTerm,proto3" json:"last_log_term,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestVote) Reset() {
	*x = RequestVote{}
	mi := &file_internal_raft_RPC_raft_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestVote) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestVote) ProtoMessage() {}

func (x *RequestVote) ProtoReflect() protoreflect.Message {
	mi := &file_internal_raft_RPC_raft_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestVote.ProtoReflect.Descriptor instead.
func (*RequestVote) Descriptor() ([]byte, []int) {
	return file_internal_raft_RPC_raft_proto_rawDescGZIP(), []int{4}
}

func (x *RequestVote) GetShardId() string {
	if x != nil {
		return x.ShardId
	}
	return ""
}

func (x *RequestVote) GetTerm() int64 {
	if x != nil {
		return x.Term
	}
	return 0
}

func (x *RequestVote) GetCandidateId() string {
	if x != nil {
		return x.CandidateId
	}
	return ""
}

func (x *RequestVote) GetLastLogIndex() int64 {
	if x != nil {
		return x.LastLogIndex
	}
	return 0
}

func (x *RequestVote) GetLastLogTerm() int64 {
	if x != nil {
		return x.LastLogTerm
	}
	return 0
}

type RequestVoteReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShardId       string                 `protobuf:"bytes,1,opt,name=shard_id,json=shardId,proto3" json:"shard_id,omitempty"`
	Term          int64                  `protobuf:"varint,2,opt,name=term,proto3" json:"term,omitempty"`
	VoteGranted   bool                   `protobuf:"varint,3,opt,name=vote_granted,json=voteGranted,proto3" json:"vote_granted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestVoteReply) Reset() {
	*x = RequestVoteReply{}
	mi := &file_internal_raft_RPC_raft_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestVoteReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestVoteReply) ProtoMessage() {}

func (x *RequestVoteReply) ProtoReflect() protoreflect.Message {
	mi := &file_internal_raft_RPC_raft_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestVoteReply.ProtoReflect.Descriptor instead.
func (*RequestVoteReply) Descriptor() ([]byte, []int) {
	return file_internal_raft_RPC_raft_proto_rawDescGZIP(), []int{5}
}

func (x *RequestVoteReply) GetShardId() string {
	if x != nil {
		return x.ShardId
	}
	return ""
}

func (x *RequestVoteReply) GetTerm() int64 {
	if x != nil {
		return x.Term
	}
	return 0
}

func (x *RequestVoteReply) GetVoteGranted() bool {
	if x != nil {
		return x.VoteGranted
	}
	return false
}

type ForwardWriteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShardId       string                 `protobuf:"bytes,1,opt,name=shard_id,json=shardId,proto3" json:"shard_id,omitempty"`
	Key           string                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Value         []byte                 `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ForwardWriteRequest) Reset() {
	*x = ForwardWriteRequest{}
	mi := &file_internal_raft_RPC_raft_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ForwardWriteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForwardWriteRequest) ProtoMessage() {}

func (x *ForwardWriteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_raft_RPC_raft_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForwardWriteRequest.ProtoReflect.Descriptor instead.
func (*ForwardWriteRequest) Descriptor() ([]byte, []int) {
	return file_internal_raft_RPC_raft_proto_rawDescGZIP(), []int{6}
}

func (x *ForwardWriteRequest) GetShardId() string {
	if x != nil {
		return x.ShardId
	}
	return ""
}

func (x *ForwardWriteRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *ForwardWriteRequest) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

type ForwardWriteReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	LeaderId      string                 `protobuf:"bytes,3,opt,name=leader_id,json=leaderId,proto3" json:"leader_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ForwardWriteReply) Reset() {
	*x = ForwardWriteReply{}
	mi := &file_internal_raft_RPC_raft_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ForwardWriteReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForwardWriteReply) ProtoMessage() {}

func (x *ForwardWriteReply) ProtoReflect() protoreflect.Message {
	mi := &file_internal_raft_RPC_raft_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForwardWriteReply.ProtoReflect.Descriptor instead.
func (*ForwardWriteReply) Descriptor() ([]byte, []int) {
	return file_internal_raft_RPC_raft_proto_rawDescGZIP(), []int{7}
}

func (x *ForwardWriteReply) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ForwardWriteReply) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *ForwardWriteReply) GetLeaderId() string {
	if x != nil {
		return x.LeaderId
	}
	return ""
}

type ForwardReadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShardId       string                 `protobuf:"bytes,1,opt,name=shard_id,json=shardId,proto3" json:"shard_id,omitempty"`
	Key           string                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ForwardReadRequest) Reset() {
	*x = ForwardReadRequest{}
	mi := &file_internal_raft_RPC_raft_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ForwardReadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForwardReadRequest) ProtoMessage() {}

func (x *ForwardReadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_raft_RPC_raft_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForwardReadRequest.ProtoReflect.Descriptor instead.
func (*ForwardReadRequest) Descriptor() ([]byte, []int) {
	return file_internal_raft_RPC_raft_proto_rawDescGZIP(), []int{8}
}

func (x *ForwardReadRequest) GetShardId() string {
	if x != nil {
		return x.ShardId
	}
	return ""
}

func (x *ForwardReadRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type ForwardReadReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	Value         []byte                 `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	LeaderId      string                 `protobuf:"bytes,4,opt,name=leader_id,json=leaderId,proto3" json:"leader_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ForwardReadReply) Reset() {
	*x = ForwardReadReply{}
	mi := &file_internal_raft_RPC_raft_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ForwardReadReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForwardReadReply) ProtoMessage() {}

func (x *ForwardReadReply) ProtoReflect() protoreflect.Message {
	mi := &file_internal_raft_RPC_raft_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForwardReadReply.ProtoReflect.Descriptor instead.
func (*ForwardReadReply) Descriptor() ([]byte, []int) {
	return file_internal_raft_RPC_raft_proto_rawDescGZIP(), []int{9}
}

func (x *ForwardReadReply) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ForwardReadReply) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *ForwardReadReply) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *ForwardReadReply) GetLeaderId() string {
	if x != nil {
		return x.LeaderId
	}
	return ""
}

type ForwardDeleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShardId       string                 `protobuf:"bytes,1,opt,name=shard_id,json=shardId,proto3" json:"shard_id,omitempty"`
	Key           string                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ForwardDeleteRequest) Reset() {
	*x = ForwardDeleteRequest{}
	mi := &file_internal_raft_RPC_raft_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ForwardDeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForwardDeleteRequest) ProtoMessage() {}

func (x *ForwardDeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_raft_RPC_raft_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForwardDeleteRequest.ProtoReflect.Descriptor instead.
func (*ForwardDeleteRequest) Descriptor() ([]byte, []int) {
	return file_internal_raft_RPC_raft_proto_rawDescGZIP(), []int{10}
}

func (x *ForwardDeleteRequest) GetShardId() string {
	if x != nil {
		return x.ShardId
	}
	return ""
}

func (x *ForwardDeleteRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type ForwardDeleteReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	LeaderId      string                 `protobuf:"bytes,3,opt,name=leader_id,json=leaderId,proto3" json:"leader_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ForwardDeleteReply) Reset() {
	*x = ForwardDeleteReply{}
	mi := &file_internal_raft_RPC_raft_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ForwardDeleteReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForwardDeleteReply) ProtoMessage() {}

func (x *ForwardDeleteReply) ProtoReflect() protoreflect.Message {
	mi := &file_internal_raft_RPC_raft_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForwardDeleteReply.ProtoReflect.Descriptor instead.
func (*ForwardDeleteReply) Descriptor() ([]byte, []int) {
	return file_internal_raft_RPC_raft_proto_rawDescGZIP(), []int{11}
}

func (x *ForwardDeleteReply) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ForwardDeleteReply) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *ForwardDeleteReply) GetLeaderId() string {
	if x != nil {
		return x.LeaderId
	}
	return ""
}

var File_internal_raft_RPC_raft_proto protoreflect.FileDescriptor

const file_internal_raft_RPC_raft_proto_rawDesc = "" +
	"\n" +
	"\x1cinternal/raft/RPC/raft.proto\x12\araftRPC\"A\n" +
	"\aCommand\x12\x0e\n" +
	"\x02op\x18\x01 \x01(\tR\x02op\x12\x10\n" +
	"\x03key\x18\x02 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x03 \x01(\fR\x05value\"J\n" +
	"\bLogEntry\x12\x12\n" +
	"\x04term\x18\x01 \x01(\x03R\x04term\x12*\n" +
	"\acommand\x18\x02 \x01(\v2\x10.raftRPC.CommandR\acommand\"\x89\x02\n" +
	"\x14AppendEntriesRequest\x12\x19\n" +
	"\bshard_id\x18\x01 \x01(\tR\ashardId\x12\x12\n" +
	"\x04term\x18\x02 \x01(\x03R\x04term\x12\x1b\n" +
	"\tleader_id\x18\x03 \x01(\tR\bleaderId\x12$\n" +
	"\x0eprev_log_index\x18\x04 \x01(\x03R\fprevLogIndex\x12\"\n" +
	"\rprev_log_term\x18\x05 \x01(\x03R\vprevLogTerm\x12+\n" +
	"\aentries\x18\x06 \x03(\v2\x11.raftRPC.LogEntryR\aentries\x12.\n" +
	"\x13leader_commit_index\x18\a \x01(\x03R\x11leaderCommitIndex\"]\n" +
	"\x12AppendEntriesReply\x12\x19\n" +
	"\bshard_id\x18\x01 \x01(\tR\ashardId\x12\x12\n" +
	"\x04term\x18\x02 \x01(\x03R\x04term\x12\x18\n" +
	"\asuccess\x18\x03 \x01(\bR\asuccess\"\xa9\x01\n" +
	"\vRequestVote\x12\x19\n" +
	"\bshard_id\x18\x01 \x01(\tR\ashardId\x12\x12\n" +
	"\x04term\x18\x02 \x01(\x03R\x04term\x12!\n" +
	"\fcandidate_id\x18\x03 \x01(\tR\vcandidateId\x12$\n" +
	"\x0elast_log_index\x18\x04 \x01(\x03R\flastLogIndex\x12\"\n" +
	"\rlast_log_term\x18\x05 \x01(\x03R\vlastLogTerm\"d\n" +
	"\x10RequestVoteReply\x12\x19\n" +
	"\bshard_id\x18\x01 \x01(\tR\ashardId\x12\x12\n" +
	"\x04term\x18\x02 \x01(\x03R\x04term\x12!\n" +
	"\fvote_granted\x18\x03 \x01(\bR\vvoteGranted\"X\n" +
	"\x13ForwardWriteRequest\x12\x19\n" +
	"\bshard_id\x18\x01 \x01(\tR\ashardId\x12\x10\n" +
	"\x03key\x18\x02 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x03 \x01(\fR\x05value\"`\n" +
	"\x11ForwardWriteReply\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x12\x1b\n" +
	"\tleader_id\x18\x03 \x01(\tR\bleaderId\"A\n" +
	"\x12ForwardReadRequest\x12\x19\n" +
	"\bshard_id\x18\x01 \x01(\tR\ashardId\x12\x10\n" +
	"\x03key\x18\x02 \x01(\tR\x03key\"u\n" +
	"\x10ForwardReadReply\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x12\x14\n" +
	"\x05value\x18\x03 \x01(\fR\x05value\x12\x1b\n" +
	"\tleader_id\x18\x04 \x01(\tR\bleaderId\"C\n" +
	"\x14ForwardDeleteRequest\x12\x19\n" +
	"\bshard_id\x18\x01 \x01(\tR\ashardId\x12\x10\n" +
	"\x03key\x18\x02 \x01(\tR\x03key\"a\n" +
	"\x12ForwardDeleteReply\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x12\x1b\n" +
	"\tleader_id\x18\x03 \x01(\tR\bleaderId2\x83\x03\n" +
	"\x04Raft\x12Q\n" +
	"\x11SendAppendEntries\x12\x1d.raftRPC.AppendEntriesRequest\x1a\x1b.raftRPC.AppendEntriesReply\"\x00\x12D\n" +
	"\x0fSendRequestVote\x12\x14.raftRPC.RequestVote\x1a\x19.raftRPC.RequestVoteReply\"\x00\x12J\n" +
	"\fForwardWrite\x12\x1c.raftRPC.ForwardWriteRequest\x1a\x1a.raftRPC.ForwardWriteReply\"\x00\x12G\n" +
	"\vForwardRead\x12\x1b.raftRPC.ForwardReadRequest\x1a\x19.raftRPC.ForwardReadReply\"\x00\x12M\n" +
	"\rForwardDelete\x12\x1d.raftRPC.ForwardDeleteRequest\x1a\x1b.raftRPC.ForwardDeleteReply\"\x00B#Z!key_value_store/internal/raft/RPCb\x06proto3"

var (
	file_internal_raft_RPC_raft_proto_rawDescOnce sync.Once
	file_internal_raft_RPC_raft_proto_rawDescData []byte
)

func file_internal_raft_RPC_raft_proto_rawDescGZIP() []byte {
	file_internal_raft_RPC_raft_proto_rawDescOnce.Do(func() {
		file_internal_raft_RPC_raft_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_raft_RPC_raft_proto_rawDesc), len(file_internal_raft_RPC_raft_proto_rawDesc)))
	})
	return file_internal_raft_RPC_raft_proto_rawDescData
}

var file_internal_raft_RPC_raft_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_internal_raft_RPC_raft_proto_goTypes = []any{
	(*Command)(nil),              // 0: raftRPC.Command
	(*LogEntry)(nil),             // 1: raftRPC.LogEntry
	(*AppendEntriesRequest)(nil), // 2: raftRPC.AppendEntriesRequest
	(*AppendEntriesReply)(nil),   // 3: raftRPC.AppendEntriesReply
	(*RequestVote)(nil),          // 4: raftRPC.RequestVote
	(*RequestVoteReply)(nil),     // 5: raftRPC.RequestVoteReply
	(*ForwardWriteRequest)(nil),  // 6: raftRPC.ForwardWriteRequest
	(*ForwardWriteReply)(nil),    // 7: raftRPC.ForwardWriteReply
	(*ForwardReadRequest)(nil),   // 8: raftRPC.ForwardReadRequest
	(*ForwardReadReply)(nil),     // 9: raftRPC.ForwardReadReply
	(*ForwardDeleteRequest)(nil), // 10: raftRPC.ForwardDeleteRequest
	(*ForwardDeleteReply)(nil),   // 11: raftRPC.ForwardDeleteReply
}
var file_internal_raft_RPC_raft_proto_depIdxs = []int32{
	0,  // 0: raftRPC.LogEntry.command:type_name -> raftRPC.Command
	1,  // 1: raftRPC.AppendEntriesRequest.entries:type_name -> raftRPC.LogEntry
	2,  // 2: raftRPC.Raft.SendAppendEntries:input_type -> raftRPC.AppendEntriesRequest
	4,  // 3: raftRPC.Raft.SendRequestVote:input_type -> raftRPC.RequestVote
	6,  // 4: raftRPC.Raft.ForwardWrite:input_type -> raftRPC.ForwardWriteRequest
	8,  // 5: raftRPC.Raft.ForwardRead:input_type -> raftRPC.ForwardReadRequest
	10, // 6: raftRPC.Raft.ForwardDelete:input_type -> raftRPC.ForwardDeleteRequest
	3,  // 7: raftRPC.Raft.SendAppendEntries:output_type -> raftRPC.AppendEntriesReply
	5,  // 8: raftRPC.Raft.SendRequestVote:output_type -> raftRPC.RequestVoteReply
	7,  // 9: raftRPC.Raft.ForwardWrite:output_type -> raftRPC.ForwardWriteReply
	9,  // 10: raftRPC.Raft.ForwardRead:output_type -> raftRPC.ForwardReadReply
	11, // 11: raftRPC.Raft.ForwardDelete:output_type -> raftRPC.ForwardDeleteReply
	7,  // [7:12] is the sub-list for method output_type
	2,  // [2:7] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_internal_raft_RPC_raft_proto_init() }
func file_internal_raft_RPC_raft_proto_init() {
	if File_internal_raft_RPC_raft_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_raft_RPC_raft_proto_rawDesc), len(file_internal_raft_RPC_raft_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_raft_RPC_raft_proto_goTypes,
		DependencyIndexes: file_internal_raft_RPC_raft_proto_depIdxs,
		MessageInfos:      file_internal_raft_RPC_raft_proto_msgTypes,
	}.Build()
	File_internal_raft_RPC_raft_proto = out.File
	file_internal_raft_RPC_raft_proto_goTypes = nil
	file_internal_raft_RPC_raft_proto_depIdxs = nil
}
